services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    restart: always
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__LOGGING__REMOTE_LOG_READER: airflow.utils.log.file_task_handler.FileTaskHandler
      AIRFLOW__WEBSERVER__SECRET_KEY: your_secret_key_123456
      AIRFLOW__CORE__FERNET_KEY: eIHyRoeVNP60mlzcM4HNflQQnxHWf7WzayMdy9hJ1lE=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    user: "0:0"
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com &&
      airflow webserver
      "

  airflow-scheduler:
    build: .
    restart: always
    user: "0:0"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__LOGGING__REMOTE_LOG_READER: airflow.utils.log.file_task_handler.FileTaskHandler
      AIRFLOW__WEBSERVER__SECRET_KEY: your_secret_key_123456
      AIRFLOW__CORE__FERNET_KEY: eIHyRoeVNP60mlzcM4HNflQQnxHWf7WzayMdy9hJ1lE=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: airflow scheduler

volumes:
  postgres-db-volume: